spring.application.name=Yes2AamuRSVP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rasudhamuppaneni@gmail.com
spring.mail.password=rR$3122037944
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
management.endpoint.info.enabled=true
management.info.build.enabled=true
management.info.git.mode=full
management.endpoints.web.exposure.include=health,info

server.port=9091

spring.datasource.url=jdbc:postgresql://postgres:CqacLsidpgaIDXiYiXCvMDPlHMrlkdkD@caboose.proxy.rlwy.net:34428/railway
spring.datasource.username=postgres
spring.datasource.password=CqacLsidpgaIDXiYiXCvMDPlHMrlkdkD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.url=jdbc:mysql://<your-db-host>.psdb.io/wedding_rsvp?sslMode=VERIFY_IDENTITY
#spring.datasource.username=<your-username>
#spring.datasource.password=<your-password>
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true

